name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-infra:
    name: Deploy Infrastructure 
    runs-on: ubuntu-latest
    environment: development 

    steps:
    - uses: actions/checkout@v2
    
  deploy-app:
      name: Deploy Application 
      needs: deploy-infra
      runs-on: ubuntu-latest
      environment: development 
  
      steps:
      - uses: actions/checkout@v2

  run-integration-tests:
      name: Run Integration Tests 
      needs: deploy-app
      runs-on: ubuntu-latest
      environment: development 
  
      steps:
      - uses: actions/checkout@v2
