name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on:
 push:
   branches:
   - main
   paths:
   - terraform/**
 pull_request:
   branches:
   - main
   paths:
   - terraform/**

env:
  TF_LOG: INFO
  toklen: ${{ secrets.CIVO_TOKEN }}

  jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init and Plan
        run: cd terraform && terraform init && terraform plan
    
      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve