name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev-deployment:
    name: Deploy Development
    runs-on: ubuntu-latest
    environment: development 

    steps:
    - uses: actions/checkout@v2
       
    - name: Deploy Infrastructure 
      run: echo "run infra!"
  
    - name: Deploy Application 
      run: echo "deploy app to kube"
    
    - name: Run Health Check  
      run: echo "Run health check"

    - name: Run Component test  
      run: echo "Test app"

  sandbox-deployment:
    name: Deploy Sandbox
    needs: dev-deployment
    runs-on: ubuntu-latest
    environment: Sandbox 

    steps:
    - uses: actions/checkout@v2
       
    - name: Deploy Infrastructure 
      run: echo "run infra!"
  
    - name: Deploy Application 
      run: echo "deploy app to kube"
    
    - name: Run Health Check  
      run: echo "Run health check"

    - name: Run Component test  
      run: echo "Test app"
  
  production-deployment:
    name: Deploy Production
    needs: sandbox-deployment
    runs-on: ubuntu-latest
    environment: Production 

    steps:
    - uses: actions/checkout@v2
       
    - name: Deploy Infrastructure 
      run: echo "run infra!"
  
    - name: Deploy Application 
      run: echo "deploy app to kube"
    
    - name: Run Health Check  
      run: echo "Run health check"

    - name: Run Component test  
      run: echo "Test app"